version: '2'
services:
  web:
    image: httpd:2.2.32
    ports:
      - "8800:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

